### ISSUE TITLE
Reference to details about sphinx documentation generation

### ISSUE THREAD

**Issue by samuelbernardolip** [indigo-dc/jenkins-pipeline-library#124]
For release/2.1.0 can't find any reference for the instructions about the sphinx documentation generation for JePL.
This is important for users that want to generate the documentation locally.

**Comment by orviz** [comment]
You can find them in the [Contribution guide](https://indigo-dc.github.io/jenkins-pipeline-library/release/2.1.0/contrib/documentation.html) section. Hope this is enough

**Comment by samuelbernardolip** [comment]
> You can find them in the [Contribution guide](https://indigo-dc.github.io/jenkins-pipeline-library/release/2.1.0/contrib/documentation.html) section. Hope this is enough

@orviz  The problem is that if that documentation is not available, there is no way to read that, since it depends on that endpoint being available (github pages).
I purpose to have the documentation generation steps and requirements in readme.md so any user could generate locally their documentation if needed.
This is also important in case online documentation is not accessible.

**Comment by orviz** [comment]
Pull request at #127

**Comment by samuelbernardolip** [comment]
Merging PR #127 didn't close this issue. Closing now.
