### ISSUE TITLE
Dockerfile is required for pushing Docker images to registry

### ISSUE THREAD

**Issue by orviz** [indigo-dc/jenkins-pipeline-library#139]
The [documentation](https://indigo-dc.github.io/jenkins-pipeline-library/release/2.1.0/user/config_file.html#docker-registry-upload-images) does not clearly state the fact that a `Dockerfile`, pointed by defining the `build` section in the `docker-compose.yml`, is _always_ required in order to successfully push a Docker image to the selected registry.

**Comment by samuelbernardolip** [comment]
Fixed by issue #149
