### ISSUE TITLE
Release 2.1.1 returns an error when calling pipelineConfig()

### ISSUE THREAD

**Issue by orviz** [indigo-dc/jenkins-pipeline-library#169]
Exception obtained:
```
hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: pipelineConfig.call() is applicable for argument types: (java.util.LinkedHashMap) values: [[configFile:.sqa/config.yml, scmConfigs:[localBranch:true], ...]]
```

Job: https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/safdadsf.sqaaas/job/main/2/console

**Comment by samuelbernardolip** [comment]
@orviz After changing the github tag plugin in the workflow, now is working as expected:
https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/safdadsf.sqaaas/job/main/19/

Previous tag was referencing the latest commit in master branch (the reference was from the triggered branch and not from current checkout during job run).
