### ISSUE TITLE
Common services evaluation in stagging deployments

### ISSUE THREAD

**Issue by samuelbernardolip** [indigo-dc/jenkins-pipeline-library#19]
In WoloxCI they define some common service docker templates that can be used by projects. This would allow faster integration and the possibility for resource optimization when deploying multiple jobs that need same services.
Some possible candidates are:
- mysql
- postgresql
- rabbitmq
- redis
- dataverse
- slurm
This would be important only for staging deployments only.
Staging deployment is defined as the environment for:
- system and integrations tests
- benchmark test can also be considered depending on the demanded resources
- validation and acceptance tests

For this we need to review the config.yml schema and Jenkinsfile template to integrate the services.

**Comment by orviz** [comment]
Closed by https://github.com/indigo-dc/jenkins-pipeline-library/issues/49
