### ISSUE TITLE
Pipeline environment setup stage fails if project's name contains a white space

### ISSUE THREAD

**Issue by davrodgon** [indigo-dc/jenkins-pipeline-library#62]
For instance:
docker-compose -f .sqa/docker-compose.yml --project-directory /var/lib/jenkins/workspace/EOSC Synergy/ up -d
No such command: Synergy/

The limitations on the project name should be documented as long as this issue is not fixed.

**Comment by samuelbernardolip** [comment]
Already implemented and corrected with #PR71.
