### ISSUE TITLE
Create Jenkins CI pipeline

### ISSUE THREAD

**Issue by orviz** [indigo-dc/jenkins-pipeline-library#8]
Identify the continuous integration checks to be done and use the current Jenkins pipeline to execute them.

**Comment by orviz** [comment]
@davrodgon any CI checks that can be done for the new implementation `2.0.0`? (apart from #3)

**Comment by davrodgon** [comment]
We can probably add some tests for the scripts, I´ll have a look at it.

**Comment by davrodgon** [comment]
Unfortunately "There is no built-in support for automated testing, and the Jenkins Handbook even suggests doing manual testing via the Jenkins web interface". But there is some stuff already we can try.
We can start with https://github.com/jenkinsci/JenkinsPipelineUnit 
and see if it works for us.
